### ISSUE TITLE
Log-in buttons

### ISSUE THREAD

**Issue by ledgeb1** [opencadc/science-platform#102]
I tried logging into ARCADE directly from the https://demo.canfar.net site by clicking on the button and when I had my previously active session it was able to connect me to ARCADE no problem. I killed the session manually to see if it would generate a new link for me, and when I tried to click on the ARCADE button and log-in again it gave me this error. When I used the new CARTA button to log-in, it sent me to my active CARTA session. I did not try to kill the CARTA session and regenerate using the button.

<img width="960" alt="2020-08-27 (1)" src="https://user-images.githubusercontent.com/67075110/91463775-c995ea00-e859-11ea-820c-20eb6dba50d7.png">

**Comment by brianmajor** [comment]
The failure on connection to your restarted Arcade (desktop) session is due to the asynchronous nature of the platform on which arcade is running: kubernetes.  This is essentially a flaw in the API of arcade and is noted in the issue here:

https://github.com/opencadc/arcade/issues/4

Your session was started but it hadn't finished initializing so the connection failed.  I believe the link would work after an indeterminate amount of time (minutes) when it has finished initializing.

Sometimes initialization takes a few seconds, sometime much longer.

Closing this issue.
