### ISSUE TITLE
New session: Pluto Notebooks

### ISSUE THREAD

**Issue by sfabbro** [opencadc/science-platform#279]
Pluto notebooks are getting popular with Julia users. Do we want to maintain a minimal Pluto notebook server?

**Comment by brianmajor** [comment]
@sefffal and I have created a pluto session container.  I have been waiting to get some of our ops team's time so that the requests go through our haproxy interface.  I will make an associated story and try to get this finished in the near future.

https://github.com/brianmajor/skaha/tree/pluto

**Comment by sefffal** [comment]
Thanks Seb and Brian for your comments, I know I personally would get use out of having Pluto working on the science platform.

**Comment by sefffal** [comment]
I've been using the Pluto session for the last week and it's working great!
I'd like to make my own docker image for Pluto with a few improvements including pre-compiling Pluto so that it launches faster.
Would you mind reminding me how to customize what command is run when the container is launched?

The `CMD` and `ENTRYPOINT` entries are ignored, right?

**Comment by brianmajor** [comment]
Hi @sefffal   Okay, great!  Yes, CMD and ENTRYPOINT are ignored.  Currently (and this isn't ideal), there is a hidden contract between the pluto session and the platform that says that file `/skaha/startup.sh` is used.  That can be seen in the `command` entry here:

https://github.com/opencadc/skaha/blob/master/deployment/k8s-config/kustomize/base/skaha/config/launch-pluto.yaml

**Comment by sfabbro** [comment]
Looks like we are good with this one. Thanks for the contribution!
