### ISSUE TITLE
User notifications when skaha configuration changes are made.

### ISSUE THREAD

**Issue by fraserw** [opencadc/science-platform#282]
Today I spent a number of hours trying to work around new configuration changes that were made since my last batch of jobs were launched. At the very least a warning that changes have been made would be useful. This would have saved most of the lost time. Better still would be to tell us what those changes are, allowing easier adjustments to skaha commands.

**Comment by brianmajor** [comment]
Hi Wes.  Yes, it is a good idea.  Since @kcasteels and I are the only ones releasing at this time, we'll take your advice and make announcements when there are changes that affect users.

If you want to get even more frequent and detailed updates you can 'watch' this skaha github repository and then receive notifications on PRs that have merged to master.  This is an indication that a release was made, but may not necessarily be user-facing.
