### ISSUE TITLE
CASA Viewer not  loading in CASA 4.7.2

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#47]
The `casaviewer` command is not working in CASA 4.7.2 container. Aborts with the following error:

```
# ~
# casa-4 $ casaviewer 
process 84: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libcasa-dbus.so.3() [0x3734645bec]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libcasa-dbus.so.3() [0x373464cf79]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libcasa-dbus.so.3() [0x373463a335]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libcasa-dbus.so.3() [0x373463a3f1]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libcasa-dbus.so.3() [0x3734648dc9]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libcasa-dbus.so.3() [0x3734634d7a]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libcasa-dbus.so.3() [0x3734634a01]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libcasa-dbus.so.3() [0x37346155b2]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libcasa-dbus.so.3() [0x373460dcc8]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libQtDBus.so.4.8.5(_ZN15QDBusConnection12connectToBusENS_7BusTypeERK7QString+0x186) [0x3739e16936]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libQtDBus.so.4.8.5(_ZN15QDBusConnection10sessionBusEv+0x8c) [0x3739e1701c]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libdisplay.so.1577.1.255(_ZN4casa13QtDataManagerC2EPNS_17QtDisplayPanelGuiEPKcP7QWidget+0x22b) [0x7f342433b79b]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/../../libdisplay.so.1577.1.255(_ZN4casa17QtDisplayPanelGui15showDataManagerEv+0x4b) [0x7f34243dd09b]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/casaviewer(main+0x1124) [0x40e304]
  /lib64/libc.so.6(__libc_start_main+0x100) [0x7f3417679d20]
  /opt/casa-release-4.7.2-el6/lib/casa/bin/casaviewer() [0x40f0e5]
Aborted (core dumped)
```

Steps to reproduce:
1. Load casa 4.7.2 container
2. Type `casaviewer`

**Comment by yeunga** [comment]
The issue is resulted from dbus uuid being missing. Added 'dbus-uuidgen --ensure' to Dockerfile to generate the dbus uuid. 

Tested the fix on el7 for all CASA versions (from version 4.5.0 to version 5.6.1-8 at time of writing) that support el7. The fix failed. It looks like the CASA versions on el7 were built with a dbus library without the version information.

---

dbus-uuidgen --ensure
dbus-uuidgen: /opt/casa-release-5.4.0-70.el7/lib/libdbus-1.so.3: no version information available (required by dbus-uuidgen)
dbus-uuidgen: /opt/casa-release-5.4.0-70.el7/lib/libdbus-1.so.3: no version information available (required by dbus-uuidgen)
dbus-uuidgen: relocation error: dbus-uuidgen: symbol _dbus_create_uuid, version LIBDBUS_PRIVATE_1.10.24 not defined in file libdbus-1.so.3 with link time reference

---

Tested the fix on el6. There was no error. Hence the CASA containers were built on el6.
