### ISSUE TITLE
CASA Version number not complete

### ISSUE THREAD

**Issue by brianmajor** [opencadc/science-platform#49]
In the title bar of the CASA windows, the minor version component of CASA is often missing.  For example, it will show 4.7 instead of 4.7.2.  The complete information is important to be displayed because there are numerous versions with the same major number.

**Comment by yeunga** [comment]
By using 'startup.sh' as suggested by Brian, this issue is fixed.

**Comment by drtobybrown** [comment]
Looking at the various casa containers, they still say casa 5 rather than casa 5.x.x...

This should be updated in the two circled regions as well.

e.g., 
<img width="522" alt="Screenshot 2020-08-21 at 12 18 28" src="https://user-images.githubusercontent.com/6336385/90929277-46821900-e3ad-11ea-83bc-f4e718390939.png">
