### ISSUE TITLE
CASA pipeline 

### ISSUE THREAD

**Issue by DazhiZhou** [opencadc/science-platform#513]
Hi all, I was trying to use the pipeline version of CASA 4.7.0 and 5.1.1-5 to reduce some archival data. It shows me some errors when I try to use the command 'casa --pipeline' in the corresponding terminal. I am not sure if it is because the the environment is only for the normal casa rather than the pipeline mode. If so, do you have any suggestions!? Many thanks!

**Comment by helenkirk** [comment]
@DazhiZhou My apologies for a slow reply... I was out of office on Friday.  The pipeline environment should work for both of those casa versions, but I am seeing strange, but different error messages on both when I try to launch them today.  Could you please let me know a little bit of the error messages you're seeing, so I can make sure we're seeing the same thing?

As an aside, I'm the main ALMA support person for the science platform and have been trying to track all of our ALMA/CASA users to understand the group, and I didn't have your name on that list.  Are you part of one of the ALMA projects on the science platform, or are you coming from a different group?  It would be helpful to know how I missed you!  

thanks!

**Comment by DazhiZhou** [comment]
Hello Helen,

Sorry for my late reply. Unfortunately, my session already expired. But yes, I also received different error messages. I thought it is due to some missing scripts... 

Here are my new errors:
4.7.0
<type 'exceptions.ImportError'>: No module named analysisUtils
Could not execute initialization file: /arc/home/dzhou/.casa/init.py

I just inquired with my colleagues and supervisor. I am afraid that we don't have any ALMA projects or groups registered on science platform. But our main focus is ALMA indeed. I just registered a group called UBC-protocluster on CANFAR. Do I need to register an ALMA project as well? Thanks!

**Comment by helenkirk** [comment]
Hi,

Thanks for confirming this.  I think it's actually two different underlying errors.  I'd started working on the 5.1.1 version fix, which is proving a bit more time-consuming than I'd thought it would be (CASA distributed both a .el6 and .el7 version, but it looks like they only included the pipeline in the .el7 version, and the .el7 version is not playing nice with the general container set-up I currently have in place).  I think the fix for 4.7.0 will be a quicker one, so I'll switch over to working on that one, to at least give you something to use sooner, and will let you know.

For the ALMA group stuff, no you don't need to set up anything new.  I'll be in touch via email shortly about stuff for that, it's all just about back-end bookkeeping on our end, so we can better get you the ALMA support you need.

**Comment by helenkirk** [comment]
Hi again Dazhi, 
A quick follow-up, the fix needed for 4.7.0 was indeed fairly easy, and it should be working now.  I'll follow-up on 5.1.1 when it's working again, but at least now you have one pipeline version to work with.

**Comment by DazhiZhou** [comment]
Thank you! Yes, both 5.1.1 and 4.7.0 work now. Thank you so much again for your great help!!!
